spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: upgroup-1
      properties[spring:
        json:
          trusted:
            packages]: com.fse.userprofile
          value:
            default:
              type]: com.fse.userprofile.model.User
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:9092
    topic: userprofile-events
  application:
    name: userprofile-messaging-service
mongo:
  service:
    url: http://localhost:8086
logging:
  level:
    web: DEBUG
server:
  port: '8087'
